version: '3.7'

services:
  web:
    build: ./ExampleAPI
    ports: 
      - 8080:80
    environment:
      MYSQL_CONNECTION_STRING: "Server=mysql;Database=${MYSQL_DATABASE};User=${MYSQL_USER};Password=${MYSQL_PASSWORD};"
    links:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysqlvolume:/var/lib/mysql

volumes:
  mysqlvolume:
    driver: local